<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<div class="box box-notice">
	Notice
	<div>
		<table>
			<tr>
				<td>test</td>
			</tr>
			<tr>
				<td>test</td>
			</tr>
			<tr>
				<td>test</td>
			</tr>
			<tr>
				<td>test</td>
			</tr>
			<tr>
				<td>test</td>
			</tr>
			<tr>
				<td>test</td>
			</tr>
			<tr>
				<td>test</td>
			</tr>
			<tr>
				<td>test</td>
			</tr>
		</table>
	</div>
</div>